In [5]:
import pandas as pd
import numpy as np
laobai_data=pd.read_csv('laobaiganjiu_600559.csv')
laobai_arr=np.array(laobai_data)


In [17]:
#检查有无字符数
for i in range(0,51):
    print(i,laobai_arr[:,i])

0 ['2025/1/3' '2025/1/2' '2024/12/31' ... '2016/4/6' '2016/4/5' '2016/4/1']
1 [20.18 20.8 21.22 ... 51.01 50.28 51.59]
2 [19.3 20.18 20.99 ... 52.07 51.4 50.24]
3 [1.3554 1.7491 1.3708 ... 0.9748 0.8775 0.9365]
4 [24349115.18 26487749.36 19871756.31 ... 1890835.95 2077530.39 2278288.1]
5 [19830907.6 17600990.2 15036566.0 ... 1944013.6 1958323.0 2390040.4]
6 [312364.82 -98018.46 -946957.89 ... -73359.93 -55886.5 -43915.66]
7 [-29.1424 -27.8344 -25.2197 ... 11.232 8.8507 6.9719]
8 [4809133.05 4743416.24 3839053.19 ... 1070736.68 1068643.7 1055257.78]
9 [75.6746 89.9792 116.3531 ... 117.7152 112.0393 118.6987]
10 [33.3333 33.3333 33.3333 ... 66.6667 66.6667 66.6667]
11 [93.5067 109.0667 125.6286 ... 196.0537 164.2517 163.7913]
12 [88.4615 103.6096 122.1397 ... 134.3581 126.7179 135.4386]
13 [85.0 97.3398 114.6143 ... 108.5613 104.4652 112.1079]
14 [204.89 205.85 206.66 ... 202.28 201.12 199.6]
15 [-571659.16 -368871.47 -461491.41 ... 79802.92 97692.02 -77059.49]
16 [429290132.54 430330424

In [16]:
#处理字符串
a=laobai_arr[:,48]
num=len(a)
b=[]
flo=[]
#处理逗号
for i in range(num):
    
    b.append(a[i].replace(",",""))
    #print(str2float(i))
#str转换浮点数
for i in range(num):
    flo.append(float(b[i]))
#保存数据
for i in range(num):
    laobai_arr[i,48]=flo[i]



In [18]:
#股票数量
stock_num=len(laobai_arr[:,1])
#目标变量
open_price_today=laobai_arr[:stock_num-1,1]#当日开盘价
open_price_yest=laobai_arr[1:stock_num,1]#昨日开盘价
list_=list(open_price_today-open_price_yest)
target=[]
#target
for i in list_:
    if i>=0:
        target.append(1)
    else:
        target.append(-1)
target=np.array(target)

In [19]:
#标准化数据
fea=laobai_arr[1:,3:]
mean=np.mean(np.array(fea),axis=0,keepdims=True)
num_samp=fea.shape[0]
fea_num=fea.shape[1]
mean,fea,fea_num,num_samp

(array([[1.1030202442461183, 21966354.06147014, 21987613.878440857,
         -9699.977091686265, -5.1078325504932165, 7761134.875913526,
         98.98315002348403, 47.10349549084095, 118.71088280883154,
         123.65867402536546, 95.1029348520428, 185.1431423203387,
         -6650.097092531588, 206211819.50704354, 64480846.95029129,
         22.072549506810624, 22.00794739314243, 22.01307421324558,
         -0.008399154532644436, -0.08795678722404877, -0.7062475340535421,
         -0.05567322686707367, -0.23057707844058214, -12.104962846406742,
         4.185063410051719e-05, -0.08760981681540628, 45.93969887270967,
         45.28109953029605, 47.2569033348994, 47.44899732268709,
         0.7471878346641571, 31.88565861907028, 48.96469426960951,
         54.96458623767059, 0.2662502113668361, 21.99340300610646,
         0.6671072334429359, 0.3071797557538752, 0.2934428839830946,
         -0.20569751056834207, -0.0003604039455143262, 100.32954114607733,
         0.07604170972287502, 

In [21]:
#标准化数据
fea=laobai_arr[1:,3:]
mean=np.mean(np.array(fea),axis=0,keepdims=True)
num_samp=fea.shape[0]
fea_num=fea.shape[1]
mean,fea,fea_num,num_samp

(array([[1.1030202442461183, 21966354.06147014, 21987613.878440857,
         -9699.977091686265, -5.1078325504932165, 7761134.875913526,
         98.98315002348403, 47.10349549084095, 118.71088280883154,
         123.65867402536546, 95.1029348520428, 185.1431423203387,
         -6650.097092531588, 206211819.50704354, 64480846.95029129,
         22.072549506810624, 22.00794739314243, 22.01307421324558,
         -0.008399154532644436, -0.08795678722404877, -0.7062475340535421,
         -0.05567322686707367, -0.23057707844058214, -12.104962846406742,
         4.185063410051719e-05, -0.08760981681540628, 45.93969887270967,
         45.28109953029605, 47.2569033348994, 47.44899732268709,
         0.7471878346641571, 31.88565861907028, 48.96469426960951,
         54.96458623767059, 0.2662502113668361, 21.99340300610646,
         0.6671072334429359, 0.3071797557538752, 0.2934428839830946,
         -0.20569751056834207, -0.0003604039455143262, 100.32954114607733,
         0.07604170972287502, 

In [22]:
#求方差
squa_s=np.sum((fea-mean)**2,axis=0)/(num_samp-1)#方差
std=[]
for i in range(fea_num):
    std.append(np.sqrt(squa_s[i]))

In [23]:
#特征标准化
stan_s=np.array(std).reshape(1,fea_num)
norm_fea=(fea-mean)/stan_s
norm_fea

array([[0.25815765917569006, 0.17136025748150926, -0.17517421373250672,
        ..., -0.6151770892892622, -0.4736956809479921,
        -0.08988553266354654],
       [0.10699823714395153, -0.079384965550086, -0.2775812187189202,
        ..., -0.6301032658307576, -0.5039901689341751,
        -0.5389286840074284],
       [-0.10405755645151314, -0.3137583385017661, -0.30600950881123884,
        ..., -0.6405463151424746, -0.49733855309373065,
        -0.4908829147278358],
       ...,
       [-0.051233671723530515, -0.7608593643149927, -0.800415576198342,
        ..., 0.1701085733478825, 0.33082054783290715,
        -1.5053878122084572],
       [-0.09011237054374771, -0.7537836708185253, -0.7998441485861894,
        ..., 0.33028807213417, 0.37079610045815314, -1.5007680267008041],
       [-0.06653741442460263, -0.7461749813309716, -0.7826040656332516,
        ..., 0.47258780467463746, 0.37000580946720935,
        -1.5247909113406004]], dtype=object)

In [24]:
X_y=np.c_[norm_fea,target]#将X和target合并
#导出数据
data_1=pd.DataFrame(X_y)
data_1.to_csv(r'norm_laobai.csv')